.param T_REF=200n
* R = 1
.param VR0=0
.param VR1=0
* N*P+S = 2*8+3 = 19
.param T_VCO=10.5623n
* S = 3 
.param VS0=1.8
.param VS1=1.8
.param VS2=0
.param VS3=0
.param VENS=1.8
* P = 8
.param VP0=1.8
.param VP1=1.8
.param VP2=1.8
.param VP3=0
.param VEN0=1.8
.param VEN1=1.8
.param VEN2=1.8
.param VEN3=0
*
.param VCPB0=1.8
.param VCPB1=0
.param VCPB2=1.8
.param VCSC=1.8
.param VRSC0=0
.param VRSC1=0
